version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "@Asd1024"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  api_gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=supersecret
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  user_service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    env_file:
      - ./user-service/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  goods_service:
    build:
      context: ./goods-service
      dockerfile: Dockerfile
    env_file:
      - ./goods-service/.env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge